// cloud/security/ephemeralSnapshots.js
// Ephemeral snapshot store with disk persistence + 7-day TTL.
// Snapshots are NEVER persisted to LTM until Shayan approves.

const fs   = require("fs");
const path = require("path");

const STORE_DIR      = path.join(__dirname, ".ephemeral_store");
const DEFAULT_TTL_MS = 7 * 24 * 60 * 60 * 1000; // 7 days

if (!fs.existsSync(STORE_DIR)) {
  fs.mkdirSync(STORE_DIR, { recursive: true });
}

const store = new Map(); // id → record

function scheduleExpiry(record) {
  if (!record || !record.id || !record.expiresAt) return;
  const delayMs = Math.max(0, Number(record.expiresAt) - Date.now()) + 1000;
  // .unref() so this (up to 7-day) timer never keeps the process alive by
  // itself — without it, a clean shutdown (or `node --test` on this file)
  // has to wait out the full delay before the process can exit.
  const timer = setTimeout(() => {
    const current = store.get(record.id);
    if (current && Date.now() >= current.expiresAt) {
      store.delete(record.id);
      removeFromDisk(record.id);
    }
  }, delayMs);
  if (typeof timer.unref === 'function') timer.unref();
}

function loadPersistedSnapshots() {
  try {
    const files = fs.readdirSync(STORE_DIR).filter((name) => name.endsWith(".json"));
    files.forEach((name) => {
      const file = path.join(STORE_DIR, name);
      try {
        const parsed = JSON.parse(fs.readFileSync(file, "utf8"));
        if (!parsed || !parsed.id) return;
        if (Number(parsed.expiresAt) <= Date.now()) {
          removeFromDisk(parsed.id);
          return;
        }
        store.set(parsed.id, parsed);
        scheduleExpiry(parsed);
      } catch (e) {
        console.warn("[ephemeralSnapshots] load failed:", e.message);
      }
    });
  } catch (e) {
    console.warn("[ephemeralSnapshots] startup scan failed:", e.message);
  }
}

// ── Disk helpers ──────────────────────────────────────────────────────────────

// IDs reaching persistToDisk/removeFromDisk are always internally generated by
// createSnapshot() below (snap_<timestamp>_<random>) — but callers like
// cloud/api/securityApproval.js pass a caller-supplied `snapshotId` straight
// through getSnapshot()/deleteSnapshot()/approveSnapshot() with no format check
// of its own; the only thing currently standing between that raw string and a
// filesystem path is that getSnapshot() happens to look it up in an in-memory
// Map first. That's an incidental, cross-file invariant, not a real guard — an
// explicit check belongs here, at the one place that actually builds a path.
const VALID_SNAPSHOT_ID_RE = /^snap_[0-9]+_[a-zA-Z0-9]+$/;
function safeSnapshotPath(id) {
  if (typeof id !== "string" || !VALID_SNAPSHOT_ID_RE.test(id)) return null;
  const resolved = path.resolve(path.join(STORE_DIR, `${id}.json`));
  if (!resolved.startsWith(path.resolve(STORE_DIR) + path.sep)) return null;
  return resolved;
}

function persistToDisk(id, record) {
  const file = safeSnapshotPath(id);
  if (!file) { console.warn("[ephemeralSnapshots] persist skipped: invalid id", id); return; }
  try {
    fs.writeFileSync(file, JSON.stringify(record));
  } catch (e) {
    console.warn("[ephemeralSnapshots] persist failed:", e.message);
  }
}

function removeFromDisk(id) {
  const file = safeSnapshotPath(id);
  if (!file) { console.warn("[ephemeralSnapshots] remove skipped: invalid id", id); return; }
  try {
    if (fs.existsSync(file)) fs.unlinkSync(file);
  } catch (e) {
    console.warn("[ephemeralSnapshots] remove failed:", e.message);
  }
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * createSnapshot
 * @param {{ data: any, meta?: Object, ttlMs?: number }}
 * @returns {Object} snapshot record
 */
function createSnapshot({ data, meta = {}, ttlMs = DEFAULT_TTL_MS }) {
  const id        = `snap_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
  const expiresAt = Date.now() + ttlMs;
  const record    = {
    id,
    data,
    meta,
    createdAt:       Date.now(),
    expiresAt,
    pendingApproval: true,
    approvedAt:      null,
  };

  store.set(id, record);
  persistToDisk(id, record);
  scheduleExpiry(record);

  return record;
}

/** getSnapshot */
function getSnapshot(id) {
  return store.get(id) || null;
}

/** listSnapshots */
function listSnapshots() {
  return [...store.values()];
}

/** listPendingSnapshots */
function listPendingSnapshots() {
  return [...store.values()].filter(r => r.pendingApproval);
}

/** deleteSnapshot */
function deleteSnapshot(id) {
  store.delete(id);
  removeFromDisk(id);
  return true;
}

/**
 * approveSnapshot
 * Marks as approved — caller must then persist to LTM/Notion.
 */
function approveSnapshot(id) {
  const rec = store.get(id);
  if (!rec) return null;
  rec.pendingApproval = false;
  rec.approvedAt      = Date.now();
  persistToDisk(id, rec);
  return rec;
}

module.exports = {
  createSnapshot,
  getSnapshot,
  listSnapshots,
  listPendingSnapshots,
  deleteSnapshot,
  approveSnapshot,
};

loadPersistedSnapshots();
